### ISSUE TITLE
The background display is not displayed correctly and the email notification can not be closed.

### ISSUE THREAD

**Issue by blackjelly** [issyrocks12/flarum-ext-filter#1]
The background display is not displayed correctly and the email notification can not be closed.
<img width="594" alt="filter-error" src="https://cloud.githubusercontent.com/assets/3167703/23865688/6bbf0df8-0851-11e7-9ae3-af92442e8fd3.png">

**Comment by issyrocks12** [comment]
I'm sorry I don't understand what you mean. What version of the extension are you running?

**Comment by blackjelly** [comment]
filter : v1.0.6.3
flarum : v0.1.0-beta.6

**Comment by issyrocks12** [comment]
What is the issue? I don't get what you are saying.

**Comment by blackjelly** [comment]
Sorry, I use the Google translation, the problem is installed after the background without text, "Email user when post is filter" option can not be closed.

**Comment by issyrocks12** [comment]
Does the switch not turn off at all, or does it turn off but the email still sends?

**Comment by blackjelly** [comment]
I can not send mail so there is no test to send, but click to close and save, refresh the page it becomes green again. It is important to set the options without text display, you can look at the above picture.

**Comment by issyrocks12** [comment]
Just pushed out 1.0.6.5 which should fix this problem. Try updating and let me know if it is fixed.

**Comment by blackjelly** [comment]
How do I update?
Use "composer update issyrocks12 / flarum-ext-filter".
Prompt "Nothing to install or update".

**Comment by issyrocks12** [comment]
just type composer update. If that doesn't work type

composer remove issyrocks12/flarum-ext-filter
then
composer require issyrocks12/flarum-ext-filter

**Comment by blackjelly** [comment]
Email settings can be closed, but set the title or did not appear.

**Comment by issyrocks12** [comment]
Restart your web server, if that doesn't work it is because it hasn't been translated to your language. I'm going to go ahead and close this issue because the underlying problem is fixed.
